apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opsforge-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sayaksatpathi/my-second-devops-project
    targetRevision: main
    path: helm/opsforge
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: opsforge
  syncPolicy:
    automated:
      prune: true
      selfHeal: true   # <- reverts manual drift automatically
    syncOptions:
      - CreateNamespace=true
