revisionHistoryLimit: 5

serviceAccount:
  create: true
  name: ""

apps:

  user-api:
    image:
      repository: 637423616189.dkr.ecr.ap-south-1.amazonaws.com/opsforge-dev/user-api
      tag: dev
      pullPolicy: IfNotPresent
    replicas: 1
    service:
      enabled: true
      port: 80
      targetPort: 8000
    existingSecret: opsforge-app-config
    env:
      LOG_LEVEL: INFO
    probes:
      enabled: true
      livenessPath: /health
      readinessPath: /ready
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 250m
        memory: 256Mi
    autoscaling:
      enabled: false
    pdb:
      enabled: false

  order-api:
    image:
      repository: 637423616189.dkr.ecr.ap-south-1.amazonaws.com/opsforge-dev/order-api
      tag: dev
      pullPolicy: IfNotPresent
    replicas: 1
    service:
      enabled: true
      port: 80
      targetPort: 8001
    existingSecret: opsforge-app-config
    env:
      LOG_LEVEL: INFO
      KAFKA_TOPIC: orders
    probes:
      enabled: true
      livenessPath: /health
      readinessPath: /ready
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 250m
        memory: 256Mi
    autoscaling:
      enabled: false
    pdb:
      enabled: false

  worker:
    image:
      repository: 637423616189.dkr.ecr.ap-south-1.amazonaws.com/opsforge-dev/worker
      tag: dev
      pullPolicy: IfNotPresent
    replicas: 1
    service:
      enabled: false
    existingSecret: ""
    env:
      KAFKA_TOPIC: orders
      KAFKA_GROUP: opsforge-workers
      MAX_RETRIES: "3"
    probes:
      enabled: false
      livenessPath: /health
      readinessPath: /ready
    resources:
      requests:
        cpu: 25m
        memory: 32Mi
      limits:
        cpu: 150m
        memory: 128Mi
    autoscaling:
      enabled: false
    pdb:
      enabled: false

securityContext:
  runAsNonRoot: true
  runAsUser: 10001
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault
