{{- range $name, $app := .Values.apps }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opsforge-{{ $name }}
  labels:
    app.kubernetes.io/name: opsforge-{{ $name }}
    app.kubernetes.io/managed-by: Helm
spec:
  revisionHistoryLimit: {{ $.Values.revisionHistoryLimit }}
  replicas: {{ $app.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: opsforge-{{ $name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: opsforge-{{ $name }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        {{- if $app.service.enabled }}
        prometheus.io/port: "{{ $app.service.targetPort }}"
        {{- else }}
        prometheus.io/port: "9100"
        {{- end }}
    spec:
      serviceAccountName: {{ $.Values.serviceAccount.name | default "opsforge" }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $name }}
          image: "{{ $app.image.repository }}:{{ $app.image.tag }}"
          imagePullPolicy: {{ $app.image.pullPolicy }}

          {{- if $app.service.enabled }}
          ports:
            - name: http
              containerPort: {{ $app.service.targetPort }}
          {{- else }}
          ports:
            - name: metrics
              containerPort: 9100
          {{- end }}

          {{- if $app.env }}
          env:
            {{- range $key, $value := $app.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}

          {{- if $app.existingSecret }}
          envFrom:
            - secretRef:
                name: {{ $app.existingSecret }}
          {{- end }}

          {{- if $app.probes.enabled }}
          readinessProbe:
            httpGet:
              path: {{ $app.probes.readinessPath }}
              port: {{ $app.service.targetPort }}
          livenessProbe:
            httpGet:
              path: {{ $app.probes.livenessPath }}
              port: {{ $app.service.targetPort }}
          {{- end }}

          resources:
            {{- toYaml $app.resources | nindent 12 }}

          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}

          {{- if eq $name "worker" }}
          command: ["python", "worker.py"]
          {{- end }}
---
{{- end }}
